AssignMate2/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from assign.sitemaps import HomeworkSitemap
from django.conf import settings
from django.conf.urls.static import static


sitemaps = {
    'homeworks': HomeworkSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('assign.urls', namespace='assign')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assign/urls.py
from django.urls import path
from . import views
from .views import add_homework
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

app_name = 'assign'

urlpatterns = [
    path('AssignMate_icon.png', RedirectView.as_view(url=staticfiles_storage.url('images/AssignMate_icon.png'))),

    path('', views.courses_list,
         name='courses_list'),  # Список всех домашних заданий, доступных пользователю

    path('courses/<int:pk>/',
         views.course_detail, name='course_detail'),

    path('tag/<str:tag_slug>/',
         views.homework_list, name='homework_list_by_tag'),  # Фильтрация домашних заданий по тегу

    path('<int:year>/<int:month>/<int:day>/<str:homework_slug>/',
         views.homework_detail,
         name='homework_detail'),

    path('<int:homework_id>/share/',
         views.homework_share, name='homework_share'),  # Поделиться домашним заданием

    path('<int:homework_id>/comment/',
         views.homework_comment, name='homework_comment'),  # Комментирование домашнего задания

    path('<int:homework_id>/submit/',
         views.submit_solution, name='submit_solution'),  # Отправка решения по домашнему заданию

    path('solution/delete/<int:solution_id>/',
         views.delete_solution, name='delete_solution'),  # Удаление решения домашнего задания

    path('add_homework/',
         add_homework, name='add_homework'),

    path('homeworks/', views.homework_list, name='homework_list'),

    path('homework/<int:homework_id>/delete/',
         views.delete_homework, name='delete_homework'),

    path('homework/<int:solution_id>/review/',
         views.review_homework, name='review_homework'),
]

assign/forms.py
from django import forms
from .models import Comment, Homework, Course, HomeworkSolution
from taggit.forms import TagField

class EmailHomeworkForm(forms.Form):
    name = forms.CharField(max_length=25)
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'body']

class HomeworkForm(forms.ModelForm):
    tags = TagField(required=False)

    class Meta:
        model = Homework
        fields = ['title', 'body', 'pdf', 'course', 'tags']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            self.fields['course'].queryset = Course.objects.filter(creator=user)

class HomeworkReviewForm(forms.ModelForm):
    class Meta:
        model = HomeworkSolution
        fields = ['grade', 'teacher_comment']
        widgets = {
            'teacher_comment': forms.Textarea(attrs={'rows': 4, 'cols': 40}),
            'grade': forms.NumberInput(attrs={'min': 0, 'max': 100})
        }

assign/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Homework, Comment, HomeworkSolution, Course, Enrollment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailHomeworkForm, CommentForm, HomeworkReviewForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.http import Http404
from AssignMate2 import settings
from .forms import HomeworkForm
from django.contrib import messages


def is_student(user):
    return hasattr(user, 'profile') and user.profile.role == 'student'


def is_teacher(user):
    return hasattr(user, 'profile') and user.profile.role == 'teacher'


@login_required
def courses_list(request):
    if is_teacher(request.user):
        courses = Course.objects.filter(creator=request.user)
    else:
        courses = Course.objects.filter(enrollments__student=request.user)

    return render(request, 'assign/course/list.html', {'courses': courses})


@login_required
def course_detail(request, pk):
    course = get_object_or_404(Course, pk=pk)  # использование pk как идентификатора для поиска курса
    if not (course.creator == request.user or Enrollment.objects.filter(course=course, student=request.user).exists()):
        raise Http404("You do not have permission to view this course.")
    homeworks = course.homeworks.all()
    return render(request, 'assign/course/detail.html', {'course': course, 'homeworks': homeworks})

def homework_list(request, tag_slug=None):
    if is_teacher(request.user):
        homework_list = Homework.objects.filter(author=request.user)
    else:
        enrolled_courses = Course.objects.filter(enrollments__student=request.user)
        homework_list = Homework.objects.filter(course__in=enrolled_courses)

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        homework_list = homework_list.filter(tags__in=[tag])
    paginator = Paginator(homework_list, 3)  # постраничная разбивка
    page_number = request.GET.get('page')
    try:
        homeworks = paginator.page(page_number)
    except PageNotAnInteger:
        homeworks = paginator.page(1)
    except EmptyPage:
        homeworks = paginator.page(paginator.num_pages)
    return render(request, 'assign/homework/list.html', {'page': page_number, 'homeworks': homeworks, 'tag': tag})


@login_required
def homework_detail(request, year, month, day, homework_slug):
    homework = get_object_or_404(Homework, slug=homework_slug,
                                 publish__year=year, publish__month=month, publish__day=day)
    if not (homework.course.creator == request.user or Enrollment.objects.filter(course=homework.course,
                                                                                 student=request.user).exists()):
        raise Http404("You do not have permission to view this homework.")

    # Используем функции для проверки роли пользователя

    if is_teacher(request.user):
        solutions = homework.solutions.all()
    else:
        solutions = homework.solutions.filter(student=request.user)

    can_submit_solution = is_student(request.user) and not solutions.exists()

    comments = homework.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.homework = homework
            new_comment.save()
    else:
        comment_form = CommentForm()


    return render(request, 'assign/homework/detail.html', {
        'homework': homework,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'can_submit_solution': can_submit_solution,
        'solutions': solutions,
        'is_teacher': is_teacher(request.user)  # передаем флаг в шаблон
    })

def homework_share(request, homework_id):
    # Извлечь пост по его идентификатору id
    homework = get_object_or_404(Homework,
                             id=homework_id,
                             status=Homework.Status.PUBLISHED)
    sent = False

    if request.method == 'POST':
        # Форма была передана на обработку
        form = EmailHomeworkForm(request.POST)
        if form.is_valid():
            # Поля формы успешно прошли валидацию
            cd = form.cleaned_data
            homework_url = request.build_absolute_url(
                homework.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
                      f"{homework.title}"
            message = f"Read {homework.title} at {homework_url}\n\n" \
                      f"{cd['name']}\'s ({cd['email']}) comments: {cd['comments']}"
            send_mail(subject, message, settings.EMAIL_HOST_USER,
                      [cd['to']])
            sent = True
    else:
        form = EmailHomeworkForm()
    return render(request, 'assign/homework/share.html', {'homework': homework,
                                                    'form': form,
                                                    'sent': sent})

@require_POST
def homework_comment(request, homework_id):
    homework = get_object_or_404(Homework,
                             id=homework_id,
                             status=Homework.Status.PUBLISHED)
    comment = None
    # Комментарий был отправлен
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Создать объект класса Comment, не сохраняя его в базе данных
        comment = form.save(commit=False)
        # Назначить пост комментарию
        comment.homework = homework
        # Сохранить комментарий в базе данных
        comment.save()
    return render(request, 'assign/homework/comment.html',
                  {'homework': homework,
                   'form': form,
                   'comment': comment})

@login_required
def submit_solution(request, homework_id):
    homework = get_object_or_404(Homework, id=homework_id)
    if not is_student(request.user):
        return redirect('')  # или страница ошибки

    if request.method == 'POST':
        answer_text = request.POST.get('answer_text')
        answer_pdf = request.FILES.get('answer_pdf', None)

        solution = HomeworkSolution(homework=homework, student=request.user, answer_text=answer_text,
                                    answer_pdf=answer_pdf)
        solution.save()

        return redirect(homework.get_absolute_url())  # Редирект на страницу домашнего задания

    return render(request, 'assign/homework/submit_solution.html', {'homework': homework})

@login_required
def delete_solution(request, solution_id):
    solution = get_object_or_404(HomeworkSolution, id=solution_id, student=request.user)
    if request.method == 'POST':
        solution.delete()
        return redirect('assign:homework_list')  # Или другой URL, куда нужно перейти после удаления
    else:
        return render(request, 'assign/homework/confirm_delete.html', {
            'solution': solution,
            'homework': solution.homework  # Добавляем объект homework в контекст
        })


@login_required
def add_homework(request):
    if request.method == 'POST':
        form = HomeworkForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            new_homework = form.save(commit=False)
            new_homework.author = request.user  # Установка автора
            new_homework.save()
            form.save_m2m()  # Сохранение связей многие-ко-многим, включая теги
            messages.success(request, 'Homework was added successfully!')
            return redirect(new_homework.get_absolute_url())
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = HomeworkForm(user=request.user)  # Передача пользователя в форму для инициализации

    return render(request, 'assign/homework/add_homework.html', {'form': form})

@login_required
def delete_homework(request, homework_id):
    homework = get_object_or_404(Homework, id=homework_id)
    course_id = homework.course.id  # сохраняем ID курса для редиректа

    if request.method == 'POST':
        if homework.author == request.user or request.user.is_superuser:
            homework.delete()
            messages.success(request, "Homework deleted successfully.")
            return redirect('assign:course_detail', pk=course_id)
        else:
            messages.error(request, "You do not have permission to delete this homework.")

    return redirect('assign:course_detail', pk=course_id)  # редирект обратно на страницу курса

@login_required
def review_homework(request, solution_id):
    solution = get_object_or_404(HomeworkSolution, pk=solution_id, homework__course__creator=request.user)

    if not is_teacher(request.user):
        raise Http404("You do not have permission to review this solution.")

    if request.method == 'POST':
        form = HomeworkReviewForm(request.POST, instance=solution)
        if form.is_valid():
            form.save()
            return redirect('assign:homework_detail', year=solution.homework.publish.year, month=solution.homework.publish.month, day=solution.homework.publish.day, homework_slug=solution.homework.slug)
    else:
        form = HomeworkReviewForm(instance=solution)

    return render(request, 'assign/homework/homework_review.html', {'form': form})

templates/assign/homework/add_homework.html
{% extends "assign/base.html" %}
{% block content %}
    <h1>Добавить задание</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Подтвердить" />
</form>
{% endblock %}

templates/assign/homework/comment.html
{% extends "assign/base.html" %}

{% block title %}Добавить комментарий{% endblock %}
<form method="post">
    {% csrf_token %}
{% block content %}
    {% if comment %}
        <h2>Комментарий был успешно добавлен.</h2>
        <p><a href="{{ homework.get_absolute_url }}">Обратно к заданию</a></p>
    {% else %}
        {% include "assign/homework/includes/comment_form.html" %}
    {% endif %}
</form>    
{% endblock %}

templates/assign/homework/confirm_delete.html
{% extends "assign/base.html" %}
{% block content %}
    <h1>Вы уверены, что хотите удалить решение?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Да, удалить"/>
        <a href="{% url 'assign:homework_detail' homework.publish.year homework.publish.month homework.publish.day homework.slug %}">Отменить</a>
    </form>
{% endblock %}

templates/assign/homework/detail.html
{% extends "assign/base.html" %}
{% load assign_tags %}

{% block title %}{{ homework.title }}{% endblock %}

{% block content %}
<h1 type="homework_title">
    {{ homework.title }} 

    {% if request.user == homework.author or request.user.is_staff %}
    <form method="post" action="{% url 'assign:delete_homework' homework.id %}">
    {% csrf_token %}
    <input style="background-color: #a02626;" type="submit" value="Удалить" />
    </form>
    {% endif %}
</h1>

<p class="date">
    Опубликовано {{ homework.publish }}, автор: {{ homework.author }}
</p>

<p>
    Курс: <a href="{% url 'assign:course_detail' pk=homework.course.id %}">{{ homework.course.title }}</a>
</p>
{{ homework.body|markdown }}

{% if homework.pdf %}
    <p><a href="{{ homework.pdf.url }}" target="_blank">Загрузить прикрепленный PDF</a></p>
{% else %}
    <p>No attached PDF.</p>
{% endif %}

<p><a href="{% url 'assign:homework_share' homework.id %}">Поделиться заданием...</a></p>

{% if can_submit_solution and not is_teacher %}
    <input type='submit' onclick="location.href='{% url 'assign:submit_solution' homework.id %}'" value="Отправить решение"/>
{% endif %}

{% if solutions %}
    <h2>Отправленные решения</h2>
    <ul>
    {% for solution in solutions %}
        <li>
            Решение {{ solution.student.username }}:
            <div>
                <div class="preformatted-text">{{ solution.answer_text|markdown }}</div>
                {% if solution.answer_pdf %}
                    <a href="{{ solution.answer_pdf.url }}">Загрузить PDF</a>
                {% endif %}
                {% if solution.grade or solution.teacher_comment %}
                    <p>Оценка: {{ solution.grade|default:"еще не оценено" }}</p>
                    <p>Комментарий: {{ solution.teacher_comment|default:"нет коментария" }}</p>
                {% endif %}
                {% if is_teacher %}
                    <a href="{% url 'assign:review_homework' solution.id %}">Оценить решение</a>
                {% endif %}
            </div>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>Пока что нет отправленных решений.</p>
{% endif %}

{% with comments.count as total_comments %}
    {% if total_comments|divisibleby:10 %}
        <h2>{{ total_comments }} комментариев</h2>
    {% elif total_comments|add:'0' == '1' %}
        <h2>{{ total_comments }} комментарий</h2>
    {% else %}
        <h2>{{ total_comments }} комментария</h2>
    {% endif %}
{% endwith %}

{% for comment in comments %}
    <div class="comment">
        <p class="info">Комментарий {{ forloop.counter }} от {{ comment.name }} в {{ comment.created }}</p>
        {{ comment.body|linebreaks }}
    </div>
{% empty %}
    <p>Пока нет комментариев.</p>
{% endfor %}
{% include "assign/homework/includes/comment_form.html" %}
{% endblock %}

templates/assign/homework/homework_review.html
{% extends "assign/base.html" %}
{% block content %}
<h2>Оценить решение</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Подтвердить"/>
</form>
{% endblock %}

templates/assign/homework/latest_homeworks.html
<ul>
    {% for homework in latest_homeworks %}
        <li>
            <a href="{{ homework.get_absolute_url }}">{{ homework.title }}</a>
        </li>
    {% endfor %}
</ul>

templates/assign/homework/list.html
{% extends "assign/base.html" %}
{% load assign_tags %}

{% block title %}Список заданий{% endblock %}
{% block content %}
<h1>Задания</h1>
{% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
{% endif %}
{% for homework in homeworks %}
    <h2>
       <a href="{{ homework.get_absolute_url }}">
           {{ homework.title }}</a>
    </h2>
    <p>Course: <a href="{% url 'assign:course_detail' pk=homework.course.id %}">{{ homework.course.title }}</a></p>
    <p class="tags">
        Tags:
        {% for tag in homework.tags.all %}
            <a href="{% url 'assign:homework_list_by_tag' tag.slug %}">
                {{ tag.name }}
            </a>
            {% if not forloop.last %}, {% endif %}
        {% endfor %}
    </p>
    <p class="date">
        Published {{ homework.publish }} by {{ homework.author }}
    </p>
    {{ homework.body|markdown|truncatewords_html:30 }}
{% endfor %}
{% include "pagination.html" with page=homeworks %}
{% endblock %}

templates/assign/homework/share.html
{% extends "assign/base.html" %}

{% block title %}Поделиться заданием{% endblock %}

{% block content %}
    {% if sent %}
        <h1>Письмо успешно отправлено</h1>
        <p>
            "{{ homework.title }}" было отправлено
            на {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Поделиться "{{ homework.title }}" по e-mail</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Отправить e-mail">
        </form>
    {% endif %}
{% endblock %}

templates/assign/homework/submit_solution.html
{% extends "assign/base.html" %}

{% block content %}
<h2>Отправить решение "{{ homework.title }}"</h2>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- Text Area for Text Response -->
    <div>
        <label for="answer_text">Ваше решение:</label>
        <textarea id="answer_text" name="answer_text" rows="10" cols="50" required></textarea>
    </div>

    <!-- File Input for PDF Upload -->
    <div>
        <label for="answer_pdf">Добавить PDF (необязательно):</label>
        <input type="file" id="answer_pdf" name="answer_pdf" accept=".pdf">
    </div>

    <!-- Submission Button -->
    <div>
        <input type="submit" value="Отправить решение " />
    </div>
</form>

{% endblock %}